/**
 * mc.js — Routes for Management Corporation (MC) Management
 * 
 * WHAT THIS FILE DOES:
 * Handles CRUD operations for Management Corporations:
 *   GET    /api/mc              → List MCs with search, filter, pagination
 *   GET    /api/mc/stats/summary → Count of MCs by status
 *   GET    /api/mc/:id          → Get single MC record
 *   POST   /api/mc              → Create new MC
 *   PATCH  /api/mc/:id          → Update an MC
 *   DELETE /api/mc/:id          → Delete an MC
 *   POST   /api/mc/bulk         → Bulk import/upsert from Excel data
 * 
 * NOTES:
 * - Uses Sequelize ORM (ManagementCorporation model)
 * - Uses Op.like (NOT Op.iLike) because SQLite doesn't support iLike.
 *   SQLite's LIKE is already case-insensitive for ASCII characters.
 */

const express = require('express');
const { Op } = require('sequelize');
const router = express.Router();
const db = require('../db');

// Destructure the model once at the top instead of re-fetching in every handler.
// This is cleaner and avoids repeating 'db.models.ManagementCorporation' everywhere.
const { ManagementCorporation } = db.models;

// ── Helper: Allowed writable columns ────────────────────────────────────────
// This list acts as a whitelist. Only these columns can be written to.
// This prevents "mass assignment" attacks where someone sends unexpected fields.
const WRITABLE_COLS = [
  // Filing / identity
  'reg_date', 'old_file_no', 'new_file_no',
  'management_corporation_name', 'address', 'plan_no',
  'units', 'residential', 'non_residential', 'service_units',
  'category', 'renewal_period',
  'agm_date', 'next_agm_date', 'renewal_date_vise', 'agm_date_vise',
  'mc', 'engineer', 'ma',
  'secretary', 'secretary_unit_no', 'treasurer', 'treasurer_unit_no',
  'agm_minutes', 'attendance', 'audited_accounts', 'final_accounts',
  'building_insurance', 'sinking_fund', 'budget_proposal',
  'town', 'municipal_council_pradeshiya_saba',
  'certificate_division_file_no', 'land_registry_approved_date', 'declaration_no',
  'email_address',

  // Columns used by the app UI (aliases / derived)
  // NOTE: Backend model already has these in managementCorporations.model.js
  'file_no', 'name', 'residential_units', 'non_residential_units', 'year', 'status',
  'created_by', 'modified_by', 'history',

  // RegistrationForm.jsx currently sends these fields but model types are TEXT/NULL.
  // Add them to whitelist so they don't get silently dropped.
  'council_members',
  'non_res_shops', 'non_res_office', 'non_res_hotel',
  'written_assurance_fulfilled',

  // Fields generated by RegistrationForm.jsx (checkboxes/booleans)
  // BUT these columns do not exist in the current Sequelize model/schema.
  // We only allow them if the DB schema actually has them.
  // To avoid silent data loss, we will ALSO add them to DB via ALTER TABLE in db.js.
  'services_lift',
  'services_fire_agreement',
  'services_generator_agreement',
  'services_insurance',

  'fac_common_parking',
  'fac_accessory_car_parcel',
  'fac_roof_top',
  'fac_gym',
  'fac_swimming_pool',
  'fac_penth_house',
  'fac_restaurant',
  'fac_super_market',
  'fac_garden',
  'fac_sauna',
  'fac_salon',
  'fac_golf_tennis',
  'fac_day_care',

  'mgmt_company_controlled',
  'mgmt_company_name',
  'mgmt_company_contact',

  'secretary_contact',
  'secretary_email',
  'treasurer_contact',
  'treasurer_email',

  // Checklist fields (MCManagement.jsx)
  'approval_note',
  'cl_reg_condo_plan',
  'cl_parcels_total',
  'cl_parcels_residential',
  'cl_parcels_office',
  'cl_parcels_shops',
  'cl_parcels_hotels',
  'cl_parcels_service',
  'cl_services_facilities',
  'cl_written_assurance',
  'cl_photocopy_condo_plan',
  'cl_photocopy_condo_plan_date',
  'cl_cma_certificate',
  'cl_cma_certificate_no',
  'cl_cma_certificate_date',
  'cl_declaration',
  'cl_declaration_no',
  'cl_declaration_date',
  'cl_agm_minutes',
  'cl_agm_minutes_date',
  'cl_attendance',
  'cl_attendance_total',
  'cl_attendance_physically',
  'cl_attendance_proxy',
  'cl_insurance',
  'cl_insurance_from',
  'cl_insurance_to',
  'cl_owners_list',
  'cl_constitution',
  'cl_bylaws',
  'cl_additional_bylaws',
  'cl_checked_by',
  'cl_checked_date',
  // page count blanks
  'cl_parcels_total_pg',
  'cl_parcels_residential_pg',
  'cl_parcels_office_pg',
  'cl_parcels_shops_pg',
  'cl_parcels_hotels_pg',
  'cl_parcels_service_pg',
  'cl_services_facilities_pg',
  'cl_written_assurance_pg',
  'cl_photocopy_condo_plan_pg',
  'cl_cma_certificate_pg',
  'cl_declaration_pg',
  'cl_agm_minutes_pg',
  'cl_attendance_pg',
  'cl_insurance_pg',
  'cl_owners_list_pg',
  'cl_constitution_pg',
  'cl_bylaws_pg',
  'cl_additional_bylaws_pg',
];

/**
 * Pick only allowed keys from the request body.
 * Converts empty strings to null (database-friendly).
 */
function pickWritable(body) {
  const out = {};
  for (const col of WRITABLE_COLS) {
    if (col in body) {
      out[col] = body[col] === '' ? null : body[col];
    }
  }
  return out;
}

/**
 * Convert numeric string fields to actual integers.
 * Handles comma-separated numbers like "1,200" → 1200.
 * Invalid values become null instead of NaN.
 */
function coerceInts(data, ...cols) {
  for (const col of cols) {
    if (col in data) {
      const v = data[col];
      if (v === null || v === undefined || v === '') {
        data[col] = null;
        continue;
      }
      const n = parseInt(String(v).replace(/,/g, ''), 10);
      data[col] = Number.isFinite(n) ? n : null;
    }
  }
  return data;
}

/**
 * Derive convenience columns from the main data fields.
 * The MC table has both 'new_file_no'/'old_file_no' and a combined 'file_no'.
 * This ensures they stay in sync.
 */
function deriveFields(data, isCreate = false) {
  if (isCreate) {
    // On create: use new_file_no or old_file_no as file_no fallback
    if (!data.file_no) data.file_no = data.new_file_no || data.old_file_no || null;
    if (!data.name) data.name = data.management_corporation_name || null;
    if (!data.residential_units && data.residential) data.residential_units = data.residential;
    if (!data.non_residential_units && data.non_residential) data.non_residential_units = data.non_residential;
  } else {
    // On update: keep derived columns in sync with source fields
    if (data.new_file_no || data.old_file_no) {
      data.file_no = data.new_file_no || data.old_file_no;
    }
    if (data.management_corporation_name) data.name = data.management_corporation_name;
    if (data.residential !== undefined) data.residential_units = data.residential;
    if (data.non_residential !== undefined) data.non_residential_units = data.non_residential;
  }
  return data;
}

// ── GET /api/mc ─ Paginated + filtered list ─────────────────────────────────
// Query params:
//   ?q=search       → search across file_no, name, address, etc.
//   ?status=Active  → filter by status
//   ?year=2024      → filter by year
//   ?category=A     → filter by category
//   ?town=Colombo   → filter by town
//   ?page=1&limit=20 → pagination
router.get('/', async (req, res) => {
  try {
    const { q, status, year, category, town, page = 1, limit = 20 } = req.query;
    const offset = (Math.max(1, Number(page)) - 1) * Math.max(1, Number(limit));

    const where = {};

    // FIX: Changed Op.iLike → Op.like.
    // SQLite does NOT support iLike (that's PostgreSQL only).
    // SQLite's LIKE is already case-insensitive for ASCII letters.
    if (q) {
      where[Op.or] = [
        { file_no: { [Op.like]: `%${q}%` } },
        { new_file_no: { [Op.like]: `%${q}%` } },
        { old_file_no: { [Op.like]: `%${q}%` } },
        { name: { [Op.like]: `%${q}%` } },
        { management_corporation_name: { [Op.like]: `%${q}%` } },
        { address: { [Op.like]: `%${q}%` } },
        { secretary: { [Op.like]: `%${q}%` } },
        { treasurer: { [Op.like]: `%${q}%` } },
        { town: { [Op.like]: `%${q}%` } },
      ];
    }

    if (status) where.status = status;
    if (year) where.year = Number(year);
    if (category) where.category = { [Op.like]: `%${category}%` };
    if (town) where.town = { [Op.like]: `%${town}%` };

    const { rows: records, count: total } = await ManagementCorporation.findAndCountAll({
      where,
      offset,
      limit: Number(limit),
      order: [['id', 'DESC']],
      raw: true,
    });

    res.json({ rows: records, total, page: Number(page), limit: Number(limit) });
  } catch (err) {
    console.error('GET /mc error:', err);
    res.status(500).json({ error: err.message });
  }
});

// ── GET /api/mc/stats/summary ─ Aggregate counts by status ──────────────────
// NOTE: This route MUST be defined before '/:id' to avoid
// Express treating "stats" as an id parameter.
router.get('/stats/summary', async (req, res) => {
  try {
    const [total, active, non_active, pending] = await Promise.all([
      ManagementCorporation.count(),
      ManagementCorporation.count({ where: { status: 'Active' } }),
      ManagementCorporation.count({ where: { status: 'Non Active' } }),
      ManagementCorporation.count({ where: { status: 'Pending' } }),
    ]);

    res.json({ total, active, non_active, pending });
  } catch (err) {
    console.error('GET /mc/stats/summary error:', err);
    res.status(500).json({ error: err.message });
  }
});

// ── GET /api/mc/:id ─ Single record ─────────────────────────────────────────
router.get('/:id', async (req, res) => {
  try {
    const record = await ManagementCorporation.findByPk(req.params.id);
    if (!record) return res.status(404).json({ error: 'Not found' });
    res.json(record.toJSON());
  } catch (err) {
    console.error('GET /mc/:id error:', err);
    res.status(500).json({ error: err.message });
  }
});

// ── POST /api/mc ─ Create one record ────────────────────────────────────────
router.post('/', async (req, res) => {
  try {
    let data = pickWritable(req.body);
    coerceInts(data, 'units', 'residential', 'non_residential', 'service_units',
      'residential_units', 'non_residential_units', 'year',
      'non_res_shops', 'non_res_office', 'non_res_hotel');
    deriveFields(data, true);

    // Validate required fields
    if (!data.file_no) {
      return res.status(400).json({ error: 'file_no is required' });
    }
    if (!data.name && !data.management_corporation_name) {
      return res.status(400).json({ error: 'name / management_corporation_name is required' });
    }

    // Helpful fallback so UI values always exist
    if (data.management_corporation_name && !data.name) {
      data.name = data.management_corporation_name;
    }


    const created_by = req.body.created_by || req.body.user_name || 'System';
    const modified_by = req.body.modified_by || created_by;
    const user_name = req.body.user_name || created_by;
    const initialHistory = [{
      name: user_name,
      action: 'Added',
      time: new Date().toISOString()
    }];

    const record = await ManagementCorporation.create({
      ...data,
      created_by,
      modified_by,
      history: JSON.stringify(initialHistory),
    });
    res.status(201).json(record.toJSON());
  } catch (err) {
    console.error('POST /mc error:', err);
    if (err.name === 'SequelizeUniqueConstraintError') {
      return res.status(409).json({ error: 'Duplicate file_no' });
    }
    res.status(500).json({ error: err.message });
  }
});

// ── PATCH /api/mc/:id ─ Update one record ───────────────────────────────────
router.patch('/:id', async (req, res) => {
  try {
    let data = pickWritable(req.body);
    coerceInts(data, 'units', 'residential', 'non_residential', 'service_units',
      'residential_units', 'non_residential_units', 'year',
      'non_res_shops', 'non_res_office', 'non_res_hotel');
    deriveFields(data, false);

    if (!Object.keys(data).length) {
      return res.status(400).json({ error: 'No fields to update' });
    }

    const record = await ManagementCorporation.findByPk(req.params.id);
    if (!record) return res.status(404).json({ error: 'Not found' });

    const modified_by = req.body.modified_by || req.body.user_name || 'System';
    const user_name = req.body.user_name || modified_by;
    let history = [];
    try {
      history = record.history ? JSON.parse(record.history) : [];
    } catch (e) {
      history = [];
    }
    history.push({
      name: user_name,
      action: 'Modified',
      time: new Date().toISOString()
    });

    await record.update({
      ...data,
      modified_by,
      history: JSON.stringify(history)
    });
    res.json(record.toJSON());
  } catch (err) {
    console.error('PATCH /mc/:id error:', err);
    res.status(500).json({ error: err.message });
  }
});

// ── POST /api/mc/bulk-delete ─ Delete multiple records by file_no ───────────
router.post('/bulk-delete', async (req, res) => {
  const { file_nos } = req.body;
  if (!Array.isArray(file_nos) || file_nos.length === 0) {
    return res.status(400).json({ error: 'file_nos must be a non-empty array' });
  }

  try {
    const deleted = await ManagementCorporation.destroy({ where: { file_no: file_nos } });
    res.json({ message: 'Deleted records', deleted });
  } catch (err) {
    console.error('POST /mc/bulk-delete error:', err.message);
    res.status(500).json({ error: 'Bulk delete failed: ' + err.message });
  }
});

// ── DELETE /api/mc ─ Delete ALL records ─────────────────────────────────────
router.delete('/', async (req, res) => {
  try {
    const deleted = await ManagementCorporation.destroy({ where: {} });
    res.json({ message: 'All MC records deleted', deleted });
  } catch (err) {
    console.error('DELETE /mc error:', err.message);
    res.status(500).json({ error: 'Failed to delete all records' });
  }
});

// ── DELETE /api/mc/:id ─ Delete one record ──────────────────────────────────
router.delete('/:id', async (req, res) => {
  try {
    const record = await ManagementCorporation.findByPk(req.params.id);
    if (!record) return res.status(404).json({ error: 'Not found' });

    await record.destroy();
    res.json({ deleted: true, id: record.id });
  } catch (err) {
    console.error('DELETE /mc/:id error:', err.message);
    res.status(500).json({ error: err.message });
  }
});

// ── POST /api/mc/bulk ─ Bulk import/upsert ──────────────────────────────────
// Accepts an array of MC records (typically from Excel import).
// For each record:
//   - If file_no doesn't exist → INSERT new row
//   - If file_no already exists → UPDATE existing row
// Uses a transaction so either ALL succeed or ALL roll back.
router.post('/bulk', async (req, res) => {
  const records = req.body;
  if (!Array.isArray(records) || !records.length) {
    return res.status(400).json({ error: 'Expected a non-empty array' });
  }

  const transaction = await db.sequelize.transaction();
  try {
    let inserted = 0;
    let updated = 0;

    for (const rawRec of records) {
      let data = pickWritable(rawRec);
      coerceInts(data, 'units', 'residential', 'non_residential', 'service_units',
        'residential_units', 'non_residential_units', 'year');
      deriveFields(data, true);

    // Skip rows without required fields
      if (!data.file_no) continue;

      // Make sure name exists for whitelist/UI display
      if (!data.name) {
        data.name = data.management_corporation_name || null;
      }

      if (!data.name) continue;


      const importUser = data.user_name || data.created_by || 'Bulk Import';
      const [instance, created] = await ManagementCorporation.findOrCreate({
        where: { file_no: data.file_no },
        defaults: {
          ...data,
          created_by: data.created_by,
          modified_by: data.modified_by,
          history: JSON.stringify([{
            name: importUser,
            action: 'Added',
            time: new Date().toISOString()
          }]),
        },
        transaction,
      });

      if (created) {
        inserted++;
      } else {
        const modified_by = data.modified_by || data.user_name || 'Bulk Import Update';
        let history = [];
        try {
          history = instance.history ? JSON.parse(instance.history) : [];
        } catch (e) {
          history = [];
        }
        history.push({
          name: modified_by,
          action: 'Modified',
          time: new Date().toISOString()
        });
        await instance.update({
          ...data,
          modified_by,
          history: JSON.stringify(history)
        }, { transaction });
        updated++;
      }
    }

    await transaction.commit();
    res.json({ success: true, inserted, updated });
  } catch (err) {
    // Roll back all changes if anything fails
    await transaction.rollback();
    console.error('POST /mc/bulk error:', err);
    res.status(500).json({ error: err.message });
  }
});

module.exports = router;